### ISSUE TITLE
Update website post onsite

### ISSUE THREAD

**Issue by zubairabid** [IIIT-ECell/megathon#52]
- [x] Remove Online, Onsite, Road from Upcoming events
- [x] Replace ticketing iframe with "Tickets for Business Hack will come soon"
- [x] Remove Road to Megathon FAQs.

**Comment by itsVagabond** [comment]
@zubairabid Can I work on it ?

**Comment by zubairabid** [comment]
@itsVagabond the issues have already been worked on by @YoogottamK, you can look for/suggest some other changes (they would have to be well implemented). Possibly something like code cleanup, or something that doesn't require much internal knowledge of the events.

**Comment by itsVagabond** [comment]
@zubairabid Okay. Will look for some suggestions.

PS - During "bundle install", it asks for some password sort of password. Which password is that ? My System's password, GitHub Profile's Password or, something else ?

**Comment by zubairabid** [comment]
@itsVagabond that would be your system password.
